services:
  # ollama:
  #   image: ollama/ollama
  #   container_name: ollama
  #   volumes:
  #     - ollama:/root/.ollama
  #   ports:
  #     - "11434:11434"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]

  open-webui:
      image: ghcr.io/open-webui/open-webui:main
      container_name: open-webui
      environment:
        - WEBUI_AUTH=False
      volumes:
        - open-webui:/app/backend/data
      ports:
        - "3000:8080"
      extra_hosts:
        - "host.docker.internal:host-gateway"
      restart: always
      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - capabilities: [gpu]

volumes:
  # ollama:
  #   external: true
  open-webui:
    external: true

